# This is a basic workflow to help you get started with Actions

name: Deploy to ITU

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.ITU_SERVER_SSH }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/*"
          REMOTE_HOST: ssh.itu.edu.tr
          REMOTE_USER: ${{ secrets.ITU_USER }}
          TARGET: ${{ secrets.ITU_TARGET }}
          EXCLUDE: ""
